[package]
name = "widgets"
version = "0.1.0"
authors = ["William Myers <mwilliammyers@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.5.13"
serde = "1.0"
serde_derive = "1.0"
log = "0.4.0"
regex = "1.0.5"
lazy_static = "1.1.0"
# tokio-async-await = "0.1.4"
warp = "0.1.6"
sysfs_gpio = "0.5"
