[package]
name = "widgets"
version = "0.1.0"
authors = ["William Myers <mwilliammyers@gmail.com>"]

[dependencies]
env_logger = "0.5.13"
log = "0.4.0"
warp = "0.1.6"
# hyper = "0.11"
# hyper-router = "0.4"

# [dev-dependencies]
# log = "0.4.0"
# env_logger = "0.5.13"
